# Data Frames

when we combine multiple series together  we get a data frame

In [ ]:
import numpy as np
import pandas as pd

Creating Data Frames

In [ ]:
data = {
'Name': ['John', 'Anna', 'Peter', 'Linda'],
'Age': [28, 34, 29, 42],
'City': ['New York', 'Paris', 'Berlin', 'London'],
'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [ ]:
df_list = [
['John', 28, 'New York', 65000],
['Anna', 34, 'Paris', 70000],
['Peter', 29, 'Berlin', 62000],
['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(df_list)

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df[['Age', 'City']]

   Age      City
0   28  New York
1   34     Paris
2   29    Berlin
3   42    London

In [ ]:
df['Department'] = ['HR', 'Finance', 'IT', 'Marketing']
df

    Name  Age      City  Salary Department
0   John   28  New York   65000         HR
1   Anna   34     Paris   70000    Finance
2  Peter   29    Berlin   62000         IT
3  Linda   42    London   85000  Marketing

In [ ]:
df.drop('Department', axis=1, inplace=True)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df.loc[0]  # Access first row by label

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [ ]:
df.loc[[2,3]][['Name', 'Salary']]  # Access specific rows and columns

    Name  Salary
2  Peter   62000
3  Linda   85000

In [ ]:
df.loc[[2,3]][['Name', 'Salary']]

    Name  Salary
2  Peter   62000
3  Linda   85000

## Conditional Statement

In [ ]:
df[df['Age'] > 30]  # Filter rows based on condition

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
df[(df['Age'] > 30) & (df["City"] == "London")] # Filter rows where Name is Linda and Age is greater than 30

    Name  Age    City  Salary
3  Linda   42  London   85000