### Finding Missing data

In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = {
'A': [1, 2, np.nan, 4, 5],
'B': [np.nan, 2, 3, 4, 5],
'C': [1, 2, 3, np.nan, np.nan],
'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [6]:
df
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [13]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

## Removing Missing Data

In [7]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [8]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [16]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [9]:
df.dropna(thresh=4)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [10]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [ ]:
value = {'A':50, 'B':0, 'C':200, 'D':10}

In [18]:
df.fillna(value=value)

      A    B      C     D
0   1.0  0.0    1.0   1.0
1   2.0  2.0    2.0  10.0
2  50.0  3.0    3.0  10.0
3   4.0  4.0  200.0  10.0
4   5.0  5.0  200.0   5.0

In [19]:
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0